### ISSUE TITLE
EE3 support

### ISSUE THREAD

**Issue by reinos** [clearbold/audit-pro#13]
Will it come?

Best,
Rein

**Comment by heymarkreeves** [comment]
Hi, @reinos! I don't even have a Devot:ee login handy to respond to your question there...I open sourced Audit Pro a while back because there wasn't a volume of sales to justify support. I'm no longer actively working with EE, so an EE3 version isn't something I'm looking to take on.

That said, it's a pretty straightforward add-on. It just has a bunch of functions for every hook I could track down in the documentation, and logs an entry in the database when each hook fires. If you wanted to give add-on dev a try, it's a pretty good starting point to work with.

Mark

**Comment by reinos** [comment]
HI @circa1977 

Ah to bad...

Well, i can give it a try ;-) What is handy, just a pull request?
